name: C/C++ CI

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install 32-bit libraries
      run: sudo apt-get install lib32stdc++6
    - name: make
      run: make
